import { defaultProps } from '../../../utils'

export default defaultProps({
  prefixCls: 'vc-carousel',
  className: '',
  adaptiveHeight: false,
  arrows: true,
  autoplay: false,
  autoplaySpeed: 3000,
  centerMode: false,
  centerPadding: '50px',
  cssEase: 'ease',
  dots: false,
  dotsClass: 'slick-dots',
  draggable: true,
  effect: 'scrollx',
  easing: 'linear',
  edgeFriction: 0.35,
  fade: false,
  focusOnSelect: false,
  infinite: true,
  initialSlide: 0,
  listWidth: null,
  lazyLoad: false,
  responsive: Array,
  rtl: false,
  slide: 'div',
  slidesToShow: 1,
  slidesToScroll: 1,
  speed: 500,
  swipe: true,
  swipeToSlide: false,
  touchMove: true,
  touchThreshold: 5,
  useCSS: true,
  variableWidth: false,
  vertical: false,
  edgeEvent: null,
  swipeEvent: null,
  beforeChange () {},
  afterChange () {},
  clickHandler () {},
  init () {}
})
